Added Static Web Page implementation
primakov127/Edu pull request #7
Opened 2021-03-15 14:36 UTC by primakov127

https://primakov127.github.io/

2021-03-19 12:02 UTC, SergeyGontsarevichITechart requested changes

2021-03-19 12:02 UTC, sergeygontsarevich commented on HTML_CSS/src/css/components/banner/banner.css
> +.banner__title span {
Please do not use html tag as a selector

2021-03-19 12:02 UTC, sergeygontsarevich commented on HTML_CSS/src/css/components/featured-section/featured-section.css
> +
remove empty code block

2021-03-19 12:02 UTC, sergeygontsarevich commented on HTML_CSS/src/css/components/mailing/mailing.css
> +.mailing__title i {
do not use html tag as a selector

2021-03-19 12:02 UTC, sergeygontsarevich commented on HTML_CSS/src/css/components/mailing/mailing.css
> +    background-color: rgb(89, 114, 117);
does the combination of border none and border-radius make sense?

2021-03-19 12:02 UTC, sergeygontsarevich commented on HTML_CSS/src/css/components/portfolio/potrfolio.css
> +}
please use short form for margin

2021-03-19 12:02 UTC, sergeygontsarevich commented on HTML_CSS/src/css/components/footer/footer.css
> +}
please use short form for margin

2021-03-19 12:02 UTC, sergeygontsarevich commented on HTML_CSS/src/css/components/mailing/mailing.css
> +    margin-top: -10px;
Please could you explain why you use a negative margin here?

2021-03-19 13:07 UTC, primakov127 commented on HTML_CSS/src/css/components/mailing/mailing.css
> +    background-color: rgb(89, 114, 117);
Yes, It does
It removes browser style and adds border-radius
reset.css does not removes all styles properly, I guess

2021-03-19 13:32 UTC, primakov127 commented on HTML_CSS/src/css/components/mailing/mailing.css
> +    margin-top: -10px;
Yes, I could
But I've preferred to remove it and change the code
Thank you

2021-03-29 08:32 UTC, SergeyGontsarevichITechart approved these changes

2021-03-29 10:27 UTC, merged